QS_UNIVERSITIES = [
    (1, 'MIT', 'USA'),
    (2, 'University of Cambridge', 'UK'),
    (3, 'University of Oxford', 'UK'),
    (4, 'Harvard University', 'USA'),
    (5, 'Stanford University', 'USA'),
    (6, 'Imperial College London', 'UK'),
    (7, 'ETH Zurich', 'Switzerland'),
    (8, 'National University of Singapore (NUS)', 'Singapore'),
    (9, 'UCL', 'UK'),
    (10, 'UC Berkeley', 'USA'),
    (11, 'University of Chicago', 'USA'),
    (12, 'University of Pennsylvania', 'USA'),
    (13, 'Cornell University', 'USA'),
    (14, 'University of Melbourne', 'Australia'),
    (15, 'Caltech', 'USA'),
    (16, 'Yale University', 'USA'),
    (17, 'Peking University', 'China'),
    (18, 'Princeton University', 'USA'),
    (19, 'UNSW Sydney', 'Australia'),
    (20, 'University of Sydney', 'Australia'),
    (21, 'University of Toronto', 'Canada'),
    (22, 'National University of Singapore', 'Singapore'),
    (23, 'Columbia University', 'USA'),
    (24, 'Tsinghua University', 'China'),
    (25, 'University of Edinburgh', 'UK'),
    (26, 'Nanyang Technological University', 'Singapore'),
    (27, 'University of Hong Kong', 'Hong Kong'),
    (28, 'Johns Hopkins University', 'USA'),
    (29, 'University of Tokyo', 'Japan'),
    (30, 'UCLA', 'USA'),
    (31, 'McGill University', 'Canada'),
    (32, 'University of Manchester', 'UK'),
    (33, 'University of Michigan-Ann Arbor', 'USA'),
    (34, 'ANU', 'Australia'),
    (35, 'University of British Columbia', 'Canada'),
    (36, 'EPFL', 'Switzerland'),
    (37, 'New York University', 'USA'),
    (38, 'King\'s College London', 'UK'),
    (39, 'Peking University', 'China'),
    (40, 'Fudan University', 'China'),
    (41, 'Imperial College Business School', 'UK'),
    (42, 'Monash University', 'Australia'),
    (43, 'University of Queensland', 'Australia'),
    (44, 'Zhejiang University', 'China'),
    (45, 'LSE', 'UK'),
    (46, 'Kyoto University', 'Japan'),
    (47, 'Delft University of Technology', 'Netherlands'),
    (48, 'Northwestern University', 'USA'),
    (49, 'Chinese University of Hong Kong', 'Hong Kong'),
    (50, 'University of Amsterdam', 'Netherlands'),
    (51, 'Shanghai Jiao Tong University', 'China'),
    (52, 'University of Bristol', 'UK'),
    (53, 'KAIST', 'South Korea'),
    (54, 'Duke University', 'USA'),
    (55, 'University of Texas at Austin', 'USA'),
    (56, 'Seoul National University', 'South Korea'),
    (57, 'University of New South Wales', 'Australia'),
    (58, 'University of Warwick', 'UK'),
    (59, 'LMU Munich', 'Germany'),
    (60, 'HKUST', 'Hong Kong'),
    (61, 'University of Washington', 'USA'),
    (62, 'Brown University', 'USA'),
    (63, 'University of California, San Diego', 'USA'),
    (64, 'University of Glasgow', 'UK'),
    (65, 'KU Leuven', 'Belgium'),
    (66, 'University of Southampton', 'UK'),
    (67, 'Technical University of Munich', 'Germany'),
    (68, 'Osaka University', 'Japan'),
    (69, 'University of Birmingham', 'UK'),
    (70, 'Yonsei University', 'South Korea'),
    (71, 'University of Leeds', 'UK'),
    (72, 'University of Western Australia', 'Australia'),
    (73, 'University of Sheffield', 'UK'),
    (74, 'University of St Andrews', 'UK'),
    (75, 'Trinity College Dublin', 'Ireland'),
    (76, 'Lund University', 'Sweden'),
    (77, 'University of Nottingham', 'UK'),
    (78, 'University of Copenhagen', 'Denmark'),
    (79, 'Sorbonne University', 'France'),
    (80, 'KTH Royal Institute of Technology', 'Sweden'),
    (81, 'Tohoku University', 'Japan'),
    (82, 'University of Auckland', 'New Zealand'),
    (83, 'University of Zurich', 'Switzerland'),
    (84, 'University of Adelaide', 'Australia'),
    (85, 'University of Helsinki', 'Finland'),
    (86, 'Uppsala University', 'Sweden'),
    (87, 'Aarhus University', 'Denmark'),
    (88, 'University of Oslo', 'Norway'),
    (89, 'Erasmus University Rotterdam', 'Netherlands'),
    (90, 'Maastricht University', 'Netherlands'),
    (91, 'University of Groningen', 'Netherlands'),
    (92, 'Leiden University', 'Netherlands'),
    (93, 'University of Geneva', 'Switzerland'),
    (94, 'University of Basel', 'Switzerland'),
    (95, 'University of Bern', 'Switzerland'),
    (96, 'University of Lausanne', 'Switzerland'),
    (97, 'University of St Gallen', 'Switzerland'),
    (98, 'HEC Paris', 'France'),
    (99, 'ESSEC Business School', 'France'),
    (100, 'ESCP Business School', 'France')
]
